version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo In the pre_build phase..
      - mvn clean test
  build:
    commands:
      - echo Build completed on `date`
      - mvn clean package
  post_build:
    commands:
      - echo Build Completed successfully
artifacts:
  file:
    - target/tyd-users-module.jar
  discard-paths: yes