spring:
  application:
    name: tyd-users-module
  datasource:
    username: postgres
    password: ashisht11
    url: jdbc:postgresql://localhost:5432/oCabBookingDb
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      pool-name: tyd-users-module-cp
      connection-timeout: 3000
      max-lifetime: 300000 #  Sets the maximum lifetime of a connection in the pool. An in-use connection will never retire. HikariCP removes it only when it is closed. The minimum value is 30000 ms (30 seconds). The default value is 1800000 ms (30 minutes)
      idle-timeout: 10000 # Sets the maximum amount of time that a connection can to sit idle in the pool. This setting only applies when minimumIdle is less than maximum-pool-size. The minimum value is 10000ms (10 seconds). The default value is 600000 (10 minutes).
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 9000
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
---
spring:
  config:
    activate:
      on-profile: aws
  aws:
    secretsmanager:
      endpoint: secretsmanager.ap-south-1.amazonaws.com
      region: ap-south-1

aws:
  secrets:
    rds: rds!db-4680ade8-b330-4815-a732-4eb84fb7bc3f
    mailing: tyd/mail